title: AICelebrity
description: Сайт за виртуални интервюта с известни личности.

url: https://aicelebrity.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

social:
  email: cxpucmob@gmail.com
#  github: 

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Начало
    url: /index.html
  - title: За AICelebrity
    url: /intro
  - title: About AICelebrity
    url: /intro-en
  - title: Контакти
    url: /contact
  - title: Съдържание
    url: /contents
  - title: Contents
    url: /contents

# disqus:
  # shortname: 
  # -github-io

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
